language: cpp

compiler:
  - clang++

os:
  - linux
  # - osx

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise
    packages:
      - libboost-dev
      - libclang1-3.8
      - libllvm3.8
      - libstdc++6
      - libstdc++-4.9-dev
      - libgcc-4.9-dev
      - libclang-common-3.8-dev
      - clang-3.8

before_install:
  - clang++ --version
  - mkdir build
  - cd build

script:
  - CXX="clang++" cmake ..
  - make
  - ls -Rla ../bin/