language: cpp

compiler:
  - clang++

os:
  - linux
  # - osx

before_install:
  - clang++ --version
  - mkdir build
  - cd build

install:
  - sudo apt-get install libboost-dev

script:
  - CXX="clang++" cmake ..
  - make
  - ls -Rla ../bin/