language: cpp

compiler:
  - clang++

os:
  - linux
  - osx

# https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-dev
      - ia32-libs

before_install:
  - clang++ --version
  - mkdir build64 build32

script:
  - cd build64
  - CXX="clang++" cmake ..
  - make
  - cd ../build32
  - CXX="clang++" cmake .. -DoptX86BUILD=ON
  - make
  - ls -la ../bin/