language: cpp

compiler:
  - clang++

os:
  - linux
  # - osx

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise
    packages:
      - libboost-dev
      - clang-3.7

before_install:
  - clang++ --version
  - mkdir build
  - cd build

script:
  - CXX="clang++" cmake ..
  - make
  - ls -Rla ../bin/