language: cpp

compiler:
  - clang++

os:
  - linux
  # - osx

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost1.59-all-dev

before_install:
  - clang++ --version
  - mkdir build
  - cd build

install:
  - CXX="clang++" bii cpp:build ..