version: 1.0.{build}

branches:
  only:
  - next

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

clone_folder: c:\projects\rp

environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
# boost.flyweight is header only, so no need of any libs 
#  BOOST_LIBRARYDIR: C:\Libraries\boost_1_69_0\lib32-msvc-14.0

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: echo Running cmake...
  - cmd: cd c:\projects\rp
  - cmd: mkdir build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" cmake .. -G "Visual Studio 14 2015"
  - cmd: if "%platform%"=="x64" cmake .. -G "Visual Studio 14 2015 Win64"
  - cmd: chdir

build:
  project: c:\projects\rp\build\rp++.sln

# this happens in the build directory: c:\projects\rp\build
after_build:
  - cmd: if "%platform%"=="Win32" if "%configuration%"=="Release" 7z a -t7z ..\rp.x86.release.7z ..\bin\%configuration%\rp-win-*
  - cmd: if "%platform%"=="Win32" if "%configuration%"=="Debug" 7z a -t7z ..\rp.x86.debug.7z ..\bin\%configuration%\rp-win-*
  - cmd: if "%platform%"=="x64" if "%configuration%"=="Release" 7z a -t7z ..\rp.x64.release.7z ..\bin\%configuration%\rp-win-*
  - cmd: if "%platform%"=="x64" if "%configuration%"=="Debug" 7z a -t7z ..\rp.x64.release.7z ..\bin\%configuration%\rp-win-*
  - cmd: chdir

artifacts:
  - path: rp.*.7z

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))