name: Builds

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest 
    strategy:
      fail-fast: false
      matrix:
        generator: ['ninja', 'msvc']

    name: Windows latest / ${{ matrix.generator }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup vs prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build with Ninja/cl
      if: matrix.generator == 'ninja'
      run: |
        cd src\build
        .\build-release.bat

    - name: Build with msvc
      if: matrix.generator == 'msvc'
      run: |
        cd src\build
        .\build-release-msvc.bat

    - name: Upload artifacts
      if: matrix.generator == 'ninja'
      uses: actions/upload-artifact@v3
      with:
        name: rp-win
        path: |
          src/build/rp-win.exe
          src/build/rp-win.pdb

  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: ['clang', 'gcc']

    name: Ubuntu Latest / ${{ matrix.compiler }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Installing dependencies
      run: |
        sudo apt-get -y update
        sudo apt install -y g++-12 ninja-build
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Build with gcc
      if: matrix.compiler == 'gcc'
      env:
        CC: gcc-12
        CXX: g++-12
      run: |
        cd src/build
        chmod u+x ./build-release.sh
        ./build-release.sh

    - name: Build with clang
      if: matrix.compiler == 'clang'
      env:
        CC: clang-17
        CXX: clang++-17
      run: |
        cd src/build
        chmod u+x ./build-release.sh
        ./build-release.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rp-lin-${{ matrix.compiler }}
        path: |
          src/build/rp-lin

  OSX:
    runs-on: macos-latest
    name: OSX Latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with clang
      env:
        CC: clang
        CXX: clang++
      run: |
        cd src/build
        chmod u+x ./build-release-osx.sh
        ./build-release-osx.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rp-osx
        path: |
          src/build/rp-osx
